export default function MadeByHumans() {
    return (
        <div className="flex flex-col min-h-screen items-center justify-center bg-slic3r-black font-sans dark:bg-slic3r-black">
                    <main className="relative w-screen min-h-screen flex flex-col px-6 sm:px-12 md:px-16 lg:px-25 pt-32 md:pt-40 py-16 md:py-32 items-center animate-page-fade-in">
                            <h2 className="font-horizon text-center text-ara-white text-3xl md:text-4xl uppercase mb-10 md:mb-10">
                                AI USE STATEMENT
                            </h2>
                            <div className="flex flex-col max-w-170 font-helvetica text-ara-white text-md text-center text-pretty">
                                <h3 className="uppercase font-bold">THIS WEBSITE WAS MADE BY HUMANS.</h3>
                                <h3 className="uppercase font-regular">NOT GENERATED BY AI.<br/> <br/> </h3>
                                <p className="font-regular">
                                    We acknowledge that AI is being increasingly used as a tool in many different fields, ranging from cancer research, finance, rapid development, and more. <br/><br/>
                                    Unfortunately, we've also seen a rise in AI being used to substitute creativity, whether it's in the form of AI-generated flyers, music, or writing. <br/><br/>
                                    As exciting of a field AI is, we also believe in human experience, expression, and touch as an inalienable part of creativity. Any work that is AI-generated, be it an event poster or a website design,
                                    is at best able to replicate and synthesise what humans already made, albeit without any emotion or synthesis of any worldview. <br/><br/>
                                    The design of this website is a culmination of everything we've contributed to this movement. In a way, we didn't just design and code a website ourselves<br/> — we created art in and of itself. <br/><br/>
                                </p>
                                <p className="font-regular tracking-wide text-chromeangels-grey">Designed with Figma and created by @sardonixworld using NextJS, a React framework.</p>
                            </div>
                    </main>
                </div>
    )
}